In [1]:
import numpy as np

In [3]:
# membuat array dengan numpy
mylist = [1, 2, 3]
myarray = np.array(mylist)
print(type(mylist))
print(type(myarray))
print(myarray.shape)
print(myarray)

<class 'list'>
<class 'numpy.ndarray'>
(3,)
[1 2 3]


In [4]:
# access data pada numpy array
mylist = [[1, 2, 3], [4, 5, 6]]
myarray = np.array(mylist)

print(myarray)
print(myarray.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
print("Baris pertama:", myarray[0])
print("Baris terakhir:", myarray[-1])

Baris pertama: [1 2 3]
Baris terakhir: [4 5 6]


In [7]:
print("Baris pertama kolom ketiga:", myarray[0][2])

Baris pertama kolom ketiga: 3


In [8]:
print("Hasilnya:", myarray[:, 2])

Hasilnya: [3 6]


In [10]:
# operasi aritmatik pada numpy array
myarray1 = np.array([2, 2, 2])
myarray2 = np.array([3, 3, 3])

print("Perjumlahan array:", myarray1 + myarray2)
print("Perkalian array:", myarray1 * myarray2)

Perjumlahan array: [5 5 5]
Perkalian array: [6 6 6]
